#!/usr/bin/env bash
#This script install Nginx server.

sudo apt-get -y update
sudo apt-get -y install nginx
file1=/usr/share/nginx/html/index.html
sudo bash -c "echo 'Hello World!' > $file1"
service nginx start
