#!/usr/bin/env bash
# This scripts sets up a load balancer

sudo apt install -y haproxy=1.5\*
file=/etc/haproxy/haproxy.cfg
sudo echo -e "frontend haproxynode
\tbind *:80
\tmode http
\tdefault_backend nodes" | sudo tee -a $file
sudo echo -e "backend nodes
\tmode http
\tbalance roundrobin
\toption forwardfor
\thttp-request set-header X-Forwarded-Port %[dst_port]
\tserver 274-web-01 52.72.30.141:80 check
\tserver 274-web-01 54.87.253.86:80 check" | sudo tee -a $file
sudo service haproxy restart
