#!/usr/bin/env bash
# This script configures Nginx to run and listen on port 80 in Ubuntu terminal.
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
