#!/usr/bin/env bash
# This does the following;
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal.

file=/var/run/myscript.pid
function finish_quit {
	sudo rm $file
	exit
}
function finish_term {
	echo 'I hate the kill command'
	sudo rm $file
	exit
}
trap finish_term SIGTERM
trap finish_quit SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT
sudo bash -c "echo $$ > $file"
while ((1))
do
	echo "To infinity and beyond"
	sleep 2
done
