#!/usr/bin/env bash
# This scripts displays "Best School" 10x using while loop and iteration on the 9th, it also displays "Hi".

counter=0

while [ $counter -le 10 ]; do
	if [ $counter -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((counter++))
done
