#!/usr/bin/env bash
# This  script that loops from 1 to 10 and displays "Bad luck" for the 4th loop iteration,
# displays "good luck" for the 8th loop iteration and displays "Best School" for the other iterations,
# using while loop (for and until are forbidden) and if, elif and else statement.

counter=0
while [ $counter -lt 10 ]
do
	if [ $counter -eq 3 ]
	then
		echo "bad luck"
	elif [ $counter -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done
